### ISSUE TITLE
Update-rules modifying dir to dirs when updating existing rules 

### ISSUE THREAD

**Issue by mohitsharma-in** [kubernetes/publishing-bot#383]
Below command 
`update-rules -branch release-1.25  -go 1.19.1 -o ./new-rules.yaml -rules https://github.com/kubernetes/kubernetes/raw/master/staging/publishing/rules.yaml`

```
rules:
- destination: code-generator
  branches:
  - name: master
    source:
      branch: master
      dir: staging/src/k8s.io/code-generator
  - name: release-1.25
    go: 1.20.8
    source:
      branch: release-1.25
      dir: staging/src/k8s.io/code-generator
``` 
to
```
rules:
- destination: code-generator
  branches:
  - name: master
    source:
      branch: master
      dirs:
      - staging/src/k8s.io/code-generator
  - name: release-1.25
    go: 1.19.1
    source:
      branch: release-1.25
      dirs:
      - staging/src/k8s.io/code-generator
  ```

This might be caused by [PR](https://github.com/kubernetes/publishing-bot/pull/337) 

CC :  @akhilerm
